version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=your-super-secret-key-change-this
      - DATABASE_URL=sqlite:///routes.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./uploads:/app/uploads
      - ./screenshots:/app/screenshots
      - ./chrome_profile:/app/chrome_profile
      - ./routes.db:/app/routes.db
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=your-super-secret-key-change-this
      - DATABASE_URL=sqlite:///routes.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./uploads:/app/uploads
      - ./screenshots:/app/screenshots
      - ./chrome_profile:/app/chrome_profile
      - ./routes.db:/app/routes.db
    depends_on:
      - redis
      - web
    restart: unless-stopped

volumes:
  redis_data: 